W3ECO-38 and W3ECO-39 home screen markup
web3eco/0xyShake pull request #4
Opened 2024-07-26 16:04 UTC by SteffQing

2024-07-26 21:56 UTC, Max-Levitskiy requested changes

2024-07-26 21:56 UTC, Max-Levitskiy commented on public/bg_game_start.png
It's a huge images, 155Kb. I told you multiple times you should create dives. I even sent you an example of the code. Why did you ignore it?

2024-07-26 21:56 UTC, Max-Levitskiy commented on public/mountain_bg.png
Why do you have this image with opacity? It increases the size. You can do opacity using CSS.

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/assets/svg/Gamepad.tsx
> +                d="M3.03335 13.1666C2.46669 13.1666 2.0278 12.9694 1.71669 12.575C1.40558 12.1805 1.28891 11.7 1.36669 11.1333L2.06669 6.13331C2.16669 5.46665 2.46391 4.91665 2.95835 4.48331C3.4528 4
Are you sure it's the best way to inject SVG in the code? How about to have a separate file, don't have it styled, don't have to put properties in JSX format?

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +        const timer = setTimeout(() => setProgress(26), 500)
why it statically coded here?

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +            {/*<StartGameButton nextGame={props.nextGame}/>*/}
don't left comments

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/components/NickName.tsx
>          console.log("SCORE", props.score)
Don't left console.log in the prod code please.

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/lib/utils.ts
utils is an antipatern name

2024-07-26 21:56 UTC, Max-Levitskiy commented on src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]) {
what does this function mean? I can't understand the name.

2024-07-26 22:08 UTC, Max-Levitskiy requested changes

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +                    <p>18,451 <span className="golosText !font-light text-sm opacity-50">to upgrade</span></p>
why it's hardcoded?

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +                <span className="text-[#FFFFFF4D]">Watering </span> 0.09
why it's hardcoded?

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +                <span className="absolute top-1/2 right-4 -translate-y-1/2 opacity-40 text-xs golosText">07h 59m</span>
why it's hardcoded?

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +                <span className="absolute top-1/2 right-4 -translate-y-1/2 opacity-40 text-xs golosText">59m</span>
why it's hardcoded?

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +            <Button className="bg-[linear-gradient(96.61deg,_#A4FF09_0%,_#06D0A0_100%)]
it have to be a component

2024-07-26 22:08 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
Everything has to be components here, that work because of changing parameters. Most of the stuff is already working and is reading from the endpoints. You need to adapt this stuff, not only create a static page.

2024-07-26 22:10 UTC, SteffQing commented on public/bg_game_start.png
I intended shrinking the image 
But I'll look at the div example you mentioned first

2024-07-26 22:11 UTC, SteffQing commented on public/mountain_bg.png
It's the way I exported it from Figma

2024-07-26 22:13 UTC, SteffQing commented on src/components/GameCard.tsx
> +        const timer = setTimeout(() => setProgress(26), 500)
I couldn't interact with the API to know the actual value. It's static, for now

2024-07-26 22:13 UTC, SteffQing commented on src/components/GameCard.tsx
> +            {/*<StartGameButton nextGame={props.nextGame}/>*/}
Will fix

2024-07-26 22:13 UTC, SteffQing commented on src/components/NickName.tsx
>          console.log("SCORE", props.score)
Understood. My bad

2024-07-26 22:14 UTC, SteffQing commented on src/lib/utils.ts
It's a format in use, when designing tailwind apps with shadcn components

2024-07-26 22:15 UTC, SteffQing commented on src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]) {
It's used to join tailwind class names together without clashes

2024-07-26 22:24 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +        const timer = setTimeout(() => setProgress(26), 500)
http://t.me/OxyShake_bot/play?startapp=ref_416770012 - as you can see, the most of values are already working. So, you broke the existing functionality.

2024-07-26 22:25 UTC, SteffQing commented on src/components/GameCard.tsx
> +                    <p>18,451 <span className="golosText !font-light text-sm opacity-50">to upgrade</span></p>
I need to understand the returns of the API

2024-07-26 22:25 UTC, Max-Levitskiy commented on src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]) {
the name `cn`... What should I think of when I see it in the code? I have no idea. :)

2024-07-26 22:26 UTC, SteffQing commented on src/components/GameCard.tsx
> +            <Button className="bg-[linear-gradient(96.61deg,_#A4FF09_0%,_#06D0A0_100%)]
Which? The button?

2024-07-26 22:48 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +            <Button className="bg-[linear-gradient(96.61deg,_#A4FF09_0%,_#06D0A0_100%)]
You see... we have a similar buttons... 
<img width="683" alt="image" src="https://github.com/user-attachments/assets/92294eec-4433-4d30-beb6-8de4f28e19d9">
Are you gonna copy-paste such stuff in every single place? :)

2024-07-27 23:46 UTC, SteffQing commented on src/components/GameCard.tsx
> +            <Button className="bg-[linear-gradient(96.61deg,_#A4FF09_0%,_#06D0A0_100%)]
The component here in this case is supposedly the Button from shadcn
But sure, I'll update it

2024-07-27 23:47 UTC, SteffQing commented on src/components/GameCard.tsx
I'll update.. 
I'll need some details about the returns of these APIs though

2024-07-28 15:36 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
> +                    <p>18,451 <span className="golosText !font-light text-sm opacity-50">to upgrade</span></p>
You already have a working code on the main branch. Can you read it and understand how it works? :)

2024-07-28 15:37 UTC, Max-Levitskiy commented on src/components/GameCard.tsx
just look at the current implementation. :)

2024-07-29 19:29 UTC, closed without merging